apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-secret-pod
  labels:
    app: mariadb
    Namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb-container
        image: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: first-secret-mariadb
            key: password

