apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-httpd
  namespace: dev
spec:
  containers:
  - name: liveness-httpd
    image: httpd
    livenessProbe:
     httpGet:
      path: /
      port: 80
          
